name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ampyiVVRoXCuOo5RJEwBY9Qc
          vercel-project-id: prj_qK14DCbbkq5eQvnTCOCKXu49HsSn
